name 'netmanagers-dnsmasq'
version '1.0.2'

author 'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source 'https://github.com/netmanagers/puppet-dnsmasq'
summary 'Puppet module for dnsmasq'
description 'This module installs and manages dnsmasq. Check README for details.'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
